// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9EetoU4VDRhQ3Z2Bdf_8GPGa0hvyU4yk',
    appId: '1:451549476056:web:89767e51df02d373c7d3ad',
    messagingSenderId: '451549476056',
    projectId: 'new-project-4786b',
    authDomain: 'new-project-4786b.firebaseapp.com',
    storageBucket: 'new-project-4786b.firebasestorage.app',
    measurementId: 'G-7V1LK8CZW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTBWvcTJnDhg71ef5uGN-r3FRxS8Ij6Hc',
    appId: '1:451549476056:android:6b74fc03b53e4d45c7d3ad',
    messagingSenderId: '451549476056',
    projectId: 'new-project-4786b',
    storageBucket: 'new-project-4786b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHYsF2Y_2EX0UJE6J6CfI9yjelC6YBl2I',
    appId: '1:451549476056:ios:3a0d10167450e454c7d3ad',
    messagingSenderId: '451549476056',
    projectId: 'new-project-4786b',
    storageBucket: 'new-project-4786b.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHYsF2Y_2EX0UJE6J6CfI9yjelC6YBl2I',
    appId: '1:451549476056:ios:3a0d10167450e454c7d3ad',
    messagingSenderId: '451549476056',
    projectId: 'new-project-4786b',
    storageBucket: 'new-project-4786b.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9EetoU4VDRhQ3Z2Bdf_8GPGa0hvyU4yk',
    appId: '1:451549476056:web:93e738815242fba5c7d3ad',
    messagingSenderId: '451549476056',
    projectId: 'new-project-4786b',
    authDomain: 'new-project-4786b.firebaseapp.com',
    storageBucket: 'new-project-4786b.firebasestorage.app',
    measurementId: 'G-YB7D92206R',
  );
}
